### ISSUE TITLE
Swipe support on web

### ISSUE THREAD

**Issue by RoyalCoder88** [GeceGibi/marqueer#10]
Hi first thanks for your great package,

I wonder if you can add **swipe** support for **web** ?

Thanks in advance!

**Comment by RoyalCoder88** [comment]
Hi @GeceGibi any news about the request? Thanks!

**Comment by GeceGibi** [comment]
Added mouse swipe support @RoyalCoder88 
please check [changelog](https://pub.dev/packages/marqueer/changelog)
