### ISSUE TITLE
Click problem

### ISSUE THREAD

**Issue by Cengizhanerturan** [GeceGibi/marqueer#13]
Hello,

In widgets wrapped with "Inkwell", on the first click, it does not detect the "onTap" method of the "Inkwell" widget, it only stops the animation. After the animation stops, the "onTap" method in "inkwell" is triggered.

```
Marqueer(
        autoStart: true,
        pps: 30,
        direction: MarqueerDirection.rtl,
        restartAfterInteractionDuration: const Duration(seconds: 2),
        restartAfterInteraction: true,
        child: Row(
          children: List.generate(10, (index) {
            return InkWell(
              onTap: () {
                debugPrint('onTap method called');
              },
              child: Text(' Marqueer text - $index | '),
            );
          }),
        ),
      )
```

**Comment by GeceGibi** [comment]
Hi @Cengizhanerturan, thanks for feedback.

It's normal behavior for marqueer. 

When user interact with marqueer and if was every touch, tap (gestures) pass to child it's cause complications.
Is user trying to interact with marqueer or trying to touch inside button it. We can't know that.

So first touch need to stop the marquuer animation, if user want to tap button in it, need to touch again.

**Comment by Cengizhanerturan** [comment]
Thank you for the answer @GeceGibi ,

In this case, can a function that returns the clicked index be added to this library so that we can use it in the "onTap" method in Inkwell?

Or can't an "onTap" function be added to the library? Can't this "onTap" function handle the index of the element used in "Marqueer.builder"?

```
Marqueer.builder(
        autoStart: true,
        pps: 30,
        direction: MarqueerDirection.rtl,
        restartAfterInteractionDuration: const Duration(seconds: 2),
        restartAfterInteraction: true,
        itemCount: 10,
        itemBuilder: (context, index) {
          return InkWell(
            onTap: () {
              debugPrint('onTap method called');
            },
            child: Text(' Marqueer text - $index | '),
          );
        },
      )
```
