### ISSUE TITLE
Child component responds to clicks

### ISSUE THREAD

**Issue by JGNS** [GeceGibi/marqueer#15]
After setting the subcomponent click event, the ideal situation is that clicking the subcomponent can respond. In fact, the scrolling is temporarily suspended and cannot respond to clicks. You must click again before it resumes scrolling to respond correctly. Is there any way to improve it?

**Comment by GeceGibi** [comment]
Hi @JGNS 

Please check new version [marqueer](https://pub.dev/packages/marqueer) and see `scrollablePointerIgnoring`. 
thanks for feedback.

**Comment by JGNS** [comment]
> Hi @JGNS
> 
> Please check new version [marqueer](https://pub.dev/packages/marqueer) and see `scrollablePointerIgnoring`. thanks for feedback.

It works perfectly and is better than any other similar ! Thanks!
