### ISSUE TITLE
'Widget?' is nullable and 'Widget' isn't.

### ISSUE THREAD

**Issue by jonlpqo** [GeceGibi/marqueer#5]
../../.pub-cache/hosted/pub.dartlang.org/marqueer-1.3.1/lib/marqueer.dart:351:20: Error: The argument type 'Widget? Function(dynamic, int)' can't be assigned to the parameter type 'Widget Function(BuildContext, int)' because 'Widget?' is nullable and 'Widget' isn't.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('../../fvm/versions/3.3.10/packages/flutter/lib/src/widgets/framework.dart').
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../fvm/versions/3.3.10/packages/flutter/lib/src/widgets/framework.dart').
      itemBuilder: _defaultItemBuilder,

**Comment by vaibhiarora03** [comment]
Hi @jonlpqo . Have you found any solution for this?
